apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hrms-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hrms-frontend-service
            port:
              number: 80
